version: "3.4"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: nginx_test
        image: $REGISTRY/$REPOSITORY/$IMAGE_NGINX
        ports:
            - 80:80
        environment:
            - TZ
