version: "3.4"

services:
    nginx:
        build:
            context: .
            dockerfile: ./docker/Dockerfile
            target: nginx_test
        image: $IMAGE_NGINX:$VERSION
        ports:
            - 80:80
        environment:
            - TZ
