name: build

on:
    push:

# Context and expression syntax for GitHub Actions
# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
env:
    REGISTRY: ghcr.io # github registry https://github.com/features/packages
    REPOSITORY: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Prepare env variables
                run: |
                    if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=latest
                        VERSION_BASE=$VERSION
                    elif [[ $GITHUB_REF == 'refs/heads/production' ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=stable
                        VERSION_BASE=$VERSION
                    elif [[ $GITHUB_REF == refs/tags/v* ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=${GITHUB_REF#refs/tags/v}
                        VERSION_BASE=stable
                    else
                        IS_IMAGE_PUSH=false
                        VERSION=${GITHUB_SHA::8}
                        VERSION_BASE=latest
                    fi
                    echo "VERSION=$VERSION" >> $GITHUB_ENV
                    echo "VERSION_BASE=$VERSION_BASE" >> $GITHUB_ENV
                    echo "IS_IMAGE_PUSH=$IS_IMAGE_PUSH" >> $GITHUB_ENV
                # see: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Cache Composer dependencies
                uses: actions/cache@v2
                with:
                    path: app/vendor
                    key: composer-vendor-dir-${{ hashFiles('app/composer.lock') }}
                    restore-keys: composer-vendor-dir-

            -   name: Docker login
                run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
                # PERSONAL_ACCESS_TOKEN used as password to github registry. Secrets managed in repository configuration.

            -   name: Build images
                run: ./bin/docker build -r $REGISTRY/$REPOSITORY -v $VERSION -b $VERSION_BASE

            -   name: List images
                run: docker images

            -   name: Run
                run: docker-compose up -d

            -   name: Test
                run: |
                    docker-compose exec -T php bash -c "ls -la"
                    if curl -s http://localhost/ | grep -q "It works!"; then
                        echo "OK"
                    else
                        echo "ERROR"
                        exit 1
                    fi

            -   name: Push images (${{ env.VERSION }})
                if: env.IS_IMAGE_PUSH == 'true'
                run: ./bin/docker push -r $REGISTRY/$REPOSITORY -v $VERSION -b $VERSION_BASE
