name: build

on:
    push:

env:
    REGISTRY: ghcr.io # github registry https://github.com/features/packages
    REPOSITORY: vstelmakh/reponame
    VERSION: ${{ github.sha }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Build and run
                run: docker-compose up --build -d

            -   name: List images
                run: docker images

            -   name: Test
                run: |
                    if curl -s http://localhost/ | grep -q "It works!"; then
                        echo "OK"
                    else
                        echo "ERROR"
                        exit 1
                    fi
