name: build

on:
    push:

# https://docs.github.com/en/free-pro-team@latest/actions/reference/context-and-expression-syntax-for-github-actions
env:
    # PERSONAL_ACCESS_TOKEN: set up in repository secrets
    REGISTRY: ghcr.io # github registry https://github.com/features/packages
    REPOSITORY: ${{ github.repository }}

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Prepare env variables
                run: |
                    if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=latest
                        VERSION_BASE=$VERSION
                    elif [[ $GITHUB_REF == 'refs/heads/production' ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=stable
                        VERSION_BASE=$VERSION
                    elif [[ $GITHUB_REF == refs/tags/v* ]]; then
                        IS_IMAGE_PUSH=true
                        VERSION=${GITHUB_REF#refs/tags/v}
                        VERSION_BASE=stable
                    else
                        IS_IMAGE_PUSH=false
                        VERSION=${GITHUB_SHA::8}
                        VERSION_BASE=latest
                    fi
                    echo "VERSION=$VERSION" >> $GITHUB_ENV
                    echo "VERSION_BASE=$VERSION_BASE" >> $GITHUB_ENV
                    echo "IS_IMAGE_PUSH=$IS_IMAGE_PUSH" >> $GITHUB_ENV
                    echo "IMAGE_NGINX=$REGISTRY/$REPOSITORY/nginx_test" >> $GITHUB_ENV
                # See: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files

            -   name: Git checkout
                uses: actions/checkout@v2

            -   name: Docker login
                run: echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
                # Secrets managed in repo configuration

            -   name: Build nginx
                run: |
                    docker pull $IMAGE_NGINX:$VERSION_BASE || echo "Base image not found in registry"
                    docker build . \
                        --file docker/Dockerfile \
                        --target nginx_test \
                        --cache-from $IMAGE_NGINX:$VERSION_BASE \
                        --tag $IMAGE_NGINX:$VERSION

            -   name: List images
                run: docker images

            -   name: Run
                run: docker-compose up -d

            -   name: Test
                run: |
                    if curl -s http://localhost/ | grep -q "It works!"; then
                        echo "OK"
                    else
                        echo "ERROR"
                        exit 1
                    fi

            -   name: Push images (${{ env.VERSION }})
                if: env.IS_IMAGE_PUSH == 'true'
                run: |
                    docker push $IMAGE_NGINX:$VERSION
